name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pipenv install
        working-directory: backend

      - name: Run linter
        run: pipenv run lint
        working-directory: backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pipenv install
        working-directory: backend

      - name: Run tests
        run: pipenv run test
        working-directory: backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pipenv install
        working-directory: backend

      - name: Build Docker image
        run: |
          docker build --tag=mp-backend:$GITHUB_SHA .
        working-directory: backend

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        run: |
          docker tag mp-backend:$GITHUB_SHA <your-account-id>.dkr.ecr.<region>.amazonaws.com/mp-backend:$GITHUB_SHA
          docker push <your-account-id>.dkr.ecr.<region>.amazonaws.com/mp-backend:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        run: |
          cd backend/k8s
          kustomize edit set image backend=<your-account-id>.dkr.ecr.<region>.amazonaws.com/mp-backend:$GITHUB_SHA
          kustomize build | kubectl apply -f -
